package com.company.SQL.AdvancedJoin;

public class Placements {

//    https://www.hackerrank.com/challenges/placements/problem?isFullScreen=true

//    SELECT STUDENTS.NAME FROM STUDENTS INNER JOIN FRIENDS ON STUDENTS.ID = FRIENDS.ID INNER JOIN PACKAGES ON FRIENDS.FRIEND_ID = PACKAGES.ID WHERE PACKAGES.SALARY > (SELECT SALARY FROM PACKAGES WHERE ID = STUDENTS.ID) ORDER BY PACKAGES.SALARY ASC;
}
